using System.Reflection;
[assembly: AssemblyTitle("Sokoban")]
[assembly: AssemblyDescription("Sokoban with procedurally generated graphics")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Nikolai Voronin")]
[assembly: AssemblyProduct("Sokoban")]
[assembly: AssemblyCopyright("Copyright © 2015-2016 Nikolai Voronin")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: AssemblyVersion("0.6.1")]
